### ISSUE TITLE
versions/ui degrade to the lowest number in the specifications

### ISSUE THREAD

**Issue by Brianthered** [c2pa-org/specifications#84]
When you change from one element in the nav-menu, the version is forced to the lowest version number selected.

For example: 
  if you start with version 2.1:
  https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html
  
  then you click on Attestations it becomes 1.4:
  https://c2pa.org/specifications/specifications/1.4/attestations/attestation.html
  
  meaning that if you then click on Content Credentials it links to 1.4:
  https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html

A couple of solutions seem to be reasonable:

1. The version could be upgraded in common as any project is released.
2. There could be a latest version.

**Comment by lrosenthol** [comment]
Two different things worth noting here...

1 - The fact that we have different documents at different versions is completely on purpose!  That is how we work as an organization - we don't force all work to complete at the same time and/or make some wait for publication due to others.

2 - The reason it maintains the lower version when you switch is by design of the Antora publishing system that we use.
